baseURL = 'https://example.org/'
languageCode = 'de-de'
title = 'Recipes'

[[menus.main]]
name = 'Ãœbersicht'
pageRef = '/recipe'
weight = 20

#[[menus.main]]
#name = 'Tags'
#pageRef = '/tags'
#weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[frontmatter]
  lastmod = [":git", ":fileModTime", ":default"]